import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.evomaster.client.java.controller.api.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import static org.evomaster.client.java.controller.db.dsl.SqlDsl.sql;
import  org.evomaster.client.java.controller.api.dto.database.operations.InsertionDto;
import  java.util.List;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
 * This file was automatically generated by EvoMaster on 2020-11-23T16:40:26.323+01:00[Europe/Paris]
 * <br>
 * The generated test suite contains 72 tests
 * <br>
 * Covered targets: 1294
 * <br>
 * Used time: 0h 1m 0s
 * <br>
 * Needed budget for current results: 73%
 * <br>
 * 
 */
public class EvoMasterTest_1m_seed_1_per_op {

    
    private static final SutHandler controller = new eu.fayder.restcountries.EMDriver();
    private static String baseUrlOfSut;
    
    
    @BeforeClass
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterClass
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @Before
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    @Test
    public void test_0_with500() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=foo&" + 
                    "codes=YRQ%3BAE")
                .then()
                .statusCode(500) // eu/fayder/restcountries/v2/rest/CountryRest_268_getCountriesJson
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_1_with500() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/sn52DD7oS")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=ycJf&" + 
                    "codes=n8")
                .then()
                .statusCode(500) // eu/fayder/restcountries/v2/rest/CountryRest_268_getCountriesJson
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/wdYz2QUDuNf6")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=KNCMJRGGqttR0PwP")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/WDddiaKAQDL")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/Dy84mxIA?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/z1g_RJp")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/u?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/bBk")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_2_with500() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/xIxKh0yaBBj33h7f")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/OpT3OtaQHWUXCqRk")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/evomaster_88_input?fields=oAB")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/5yRnOVEu")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=ECZrD")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=evomaster_89_input&" + 
                    "codes=TaN")
                .then()
                .statusCode(500) // eu/fayder/restcountries/v2/rest/CountryRest_268_getCountriesJson
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_3() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/SicA")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_4() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=IMO%3BVG%3BTN0")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_5() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/De?fields=")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_6() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/DK")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_7() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/ssW?fields=foq")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_8() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=8V")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/lMh")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/T4MDbtKiQ3gy")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_9() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=8")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/0i")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_10() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=8V")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/0")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_11() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/sI?fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_12() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_13() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/Y?fields=3yjt")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_14() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=capital%3BnativeName%3Blatlng")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_15() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/xIxKh0yaBBj33h7f")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/OpT3OtaQHWUXCqRk")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/8afontdsyr?fields=oAB")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/5yRnOVEu")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=ECZrD")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=&" + 
                    "codes=TaN")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_16() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/Caribbean")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_17() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/Europe")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_18() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/Bujumbura")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_19() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/500")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_20() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/ZJzdAIGEReW8")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/NmkJTkPRISxRy2z")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/QKaAijcLSpkYBNz")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/v2howrD")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/FW")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/iVbzVFQpUI?fields=Ih6mvo")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/UprpK7hkVAZ?fields=9Mp6BRT8eZr3wh")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_21() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/RPnZtJEBHhhi7")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/WH?fields=7Z")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/NcaaqXmS")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/WFckbSy8SREUna")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/xoPQiwPqhgQ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/Torz")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=Q7675avRhun0aY")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=EW")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/QVjiI2AeDWFhZVWS")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_22() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/SV")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_23() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=IMN%3BVG%3BTN")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_24() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/Northern%20Africa?fields=gini")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_25() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/Americas")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_26() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/Taipei?fields=numericCode")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_27() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/55?fields=currencies%3Balpha3Code%3Bflag")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_28() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/ss")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_29() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/DK?fields=translations")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_30() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/TND")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_31() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/GYD")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_32() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/ga")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_33() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/Algeria?fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_34() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/French%20Guiana")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_35() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=IRQ%3BAE")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_36() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/Tongan?fields=capital")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_37() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/EFTA")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_38() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/%5C")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }
    
    
    @Test
    public void test_39() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/EF%5CA?fields=foo")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }
    
    
    @Test
    public void test_40() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/M7ipJtTl%5Ccy")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }
    
    
    @Test
    public void test_41() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/%5Caipei?fields=Taipei")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }
    
    
    @Test
    public void test_42() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/k%5C")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }
    
    
    @Test
    public void test_43() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/%5C?" + 
                    "fields=3yjt&" + 
                    "fullText=false")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }
    
    
    @Test
    public void test_44() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/%5Eujumcu%5Ca")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }
    
    
    @Test
    public void test_45() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/hSq77?fields=duUgjOju")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_46() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/DNTdyM2LObZsOJ")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_47() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=CVAQ5vdHgllTn")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_48() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/djAqIIwVUaZZSZg")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_49() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=qWSo")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_50() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/TWUsazKtn")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_51() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=veg2oNOYH&" + 
                    "codes=1")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/S0XuP31GFZ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/H5o1QW2p2Ua")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_52() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/2qYdk9")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/qVv7xdyz8?fields=jJhrDB")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/iR6is0FlHZ6p")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/o")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_53() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/0s6g")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/GqOcCuu?fields=U82rK14I1cIN")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/2W?fields=Ek7YnGYTSkNeu0")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/tcn")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=Y97nPAe")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_54() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/vGwqVVRzl_E")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_55() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/zMAw_b6P")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_56() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/jeESkme?fields=AGbJtYqjsBIGEBK")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_57() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/cX4tM")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_58() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/q7YxtMGZsdb?fields=28vq7g")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_59() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/xuoyC3YOje62qq")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_60() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/CYD")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_61() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/liW00U2")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_62() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/9")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_63() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/XcrBgBlgNn0JP")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_64() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/lfKJ9")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_65() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/yP?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_66() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/TNE")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_67() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/y42zpePxECQy")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_68() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/;M?fields=uranslation")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("");
    }
    
    
    @Test
    public void test_69() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/WiTcNLx")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_70() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/u6b5bB5Ky5lPRHCy?fields=pdfdMjPoowCb")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_71() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/gP8?fields=2X6D2XD3pNZn")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


}
