import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.evomaster.client.java.controller.api.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import static org.evomaster.client.java.controller.db.dsl.SqlDsl.sql;
import  org.evomaster.client.java.controller.api.dto.database.operations.InsertionDto;
import  java.util.List;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
 * This file was automatically generated by EvoMaster on 2020-11-23T23:28:55.629+01:00[Europe/Paris]
 * <br>
 * The generated test suite contains 92 tests
 * <br>
 * Covered targets: 1287
 * <br>
 * Used time: 0h 15m 0s
 * <br>
 * Needed budget for current results: 26%
 * <br>
 *
 */
public class EvoMasterTest_15m {


    private static final SutHandler controller = new eu.fayder.restcountries.EMDriver();
    private static String baseUrlOfSut;


    @BeforeClass
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
                .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
                .redirect(redirectConfig().followRedirects(false));
    }


    @AfterClass
    public static void tearDown() {
        controller.stopSut();
    }


    @Before
    public void initTest() {
        controller.resetStateOfSUT();
    }




    @Test
    public void test_0_with500() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=CugYrBMLqXEmLUYS&" +
                        "codes=ZDR")
                .then()
                .statusCode(500) // eu/fayder/restcountries/v2/rest/CountryRest_268_getCountriesJson
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_1_with500() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=evomaster_1882_input&" +
                        "codes=ZDR")
                .then()
                .statusCode(500) // eu/fayder/restcountries/v2/rest/CountryRest_268_getCountriesJson
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/FA%5Ch")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }


    @Test
    public void test_2_with500() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/sq")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/hU")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=evomaster_9051_input&" +
                        "codes=CUU")
                .then()
                .statusCode(500) // eu/fayder/restcountries/v2/rest/CountryRest_268_getCountriesJson
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_3_with500() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/0w8fuPQFgdvpGZP?fields=3x3C_thiKdjfvPEt")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=emJ7V&" +
                        "codes=a7y")
                .then()
                .statusCode(500) // eu/fayder/restcountries/v2/rest/CountryRest_268_getCountriesJson
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_4_with500() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/xyaKB")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/hE")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/EkRZQD")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/h5VOKJDwLK")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/iF0zlSQ2k_X2Aec?fields=oQZEnLbAVBZTKBs5")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=A&" +
                        "codes=oU")
                .then()
                .statusCode(500) // eu/fayder/restcountries/v2/rest/CountryRest_268_getCountriesJson
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/GH")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/rGGfhCfjIWN7")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_5() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/AU?fields=AM9CnjLC")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_6() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/L")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_7() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/sg?" +
                        "fields=g&" +
                        "fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_8() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=ZDQ")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_9() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/Qa?fields=eKgoSycbW")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_10() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/GA")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_11() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/aG")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_12() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/tj?fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_13() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=qvokIsterU%3C%3BU%3AUinpuU")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_14() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/southern%20asia")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_15() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/683")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_16() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/TSn?fields=opbq8ESEtIT")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_17() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=evomaster_1885_input&" +
                        "codes=evomaster_1903_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/LU?fields=")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_18() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/Sek")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_19() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/dutch")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_20() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/americas")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/ST")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/asia?fields=evomaster_229_input")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_21() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/oceania")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/xkX35U")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/evomaster_230_input?fields=evomaster_229_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_22() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/9scT2tE2")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/Ohp2Rv")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/BS?fields=BgaGtx8KjVdaJV")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_23() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/oceania")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/evomaster_1548_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/xkX35U?fields=SluGd94bX8mQa")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/asia?fields=evomaster_229_input")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_24() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/_9ME4IavsjbzY")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=ag")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/MJCUqW62TK_K")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/_aZot6")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/kSWq4dpy0M9s")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_25() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/u2BQiD6G4el9g?fields=kO0x")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/lcVPU")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/2aXTXRoWYlg")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/gP")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/Bm_Ht")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/1BKnkJZdmUme8")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_26() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/3yD0Hv8JgTsUP5?fields=J5PvjOlCOUw89D")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/I83wJzgD")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/8O6Zzho")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/ms")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/9sjbp3U")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/GsX19nX")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_27() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_28() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/evomaster_302_input?fields=P0V6D3")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/evomaster_303_input?fields=GkhUvXb1JLWN")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/evomaster_304_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=GhVAVheQWaxsbJJ&" +
                        "codes=vz1aeXubr3DZ")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=wYc")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_29() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/melanesia?fields=evomaster_1676_input")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/evomaster_1522_input?fields=evomaster_1521_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=evomaster_1514_imput")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/bandar%20seri%20begawan")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/to?" +
                        "fields=fsHvoaFqs&" +
                        "fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/qA?fields=evomaster_1677_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_30() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/oceania")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=%3BEIaovA")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/evomaster_3053_input?fields=")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/evomaster_3054_input?fields=SluGd94bX8mQa")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/asia?fields=evomaster_229_input")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_31() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/9eRGK9iLka2Fd")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/XNk")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/azmS")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/l?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_32() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/;scT2tE2")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/UD27dB1_i")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/evomaster_4705_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/BS?fields=BgaGtx8KjVdaJV")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_33() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/jbE_m")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=6XnNS8aDzc")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/hrK")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/IlgjkfkKFZ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/DJ4dlMpU74")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_34() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/GJOKsSigDFt?fields=ieeQ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/AU")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/8nr_YOHbMZk")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/PnidiJU5")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_35() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/aC44TJOImpUqp")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/ua?fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/T8N")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/qZT6gXrfo5")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/rlB8uP")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/4?fields=Pj2DOP9CEDvq4")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_36() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=vySwiRc5")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/TnkJpxzm6YR4InX")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=9e1JtKdFdpzuP9e&" +
                        "codes=7B3lpMPo1")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/YPlThTVE0bA_1bgQ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/ch8Y")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/p")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/EWXBzRMuzMJ?fields=zdPV_Bk4dVe")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_37() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/64")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/3eijf")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/10F")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/EG8GVYAy")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/b")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/iAKhAGVM?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_38() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/KFLuQ7LpVJifeJ?fields=evomaster_10648_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/357")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/evomaster_10827_input?fields=mI6K")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/Uifa?fields=%C2%80so")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/%5CW2Cyq")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/c")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=ld7v&" +
                        "codes=qHyn71mLx0")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=ztDRGh3Dka3NAe2")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_39() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/zJd3xzuDS")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=lKfjk&" +
                        "codes=kCgcJHiLu1eMf")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/E?fields=aRu3")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/w4lhsEjPoVKcQ3NK")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/1V0isV0M")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/rpa2x")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_40() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/UDvM1LnN5J")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/6eL?fields=AhiLcvqEUURBCBg")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/hj8bq?fields=1_SPjE9UmB911a7e")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/sIqY2VGN4EbS4_")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_41() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/EOHz0FGvgZf")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/SPmBY7o")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/P_s8gNDjSaMi?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/iMRE")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/_qBUoVcXxABqw")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/F7JKUcc9ZBx?fields=nJbgO7h64jvtcnJ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=ir4Hh")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_42() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/nRZs8uGWNb9")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/3HaiUqvJxc_o")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/jT3AJQ5neMlB")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/Jfuj3xZ9")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/XzUpVehTL_XiUm0")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/NI")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/2Y")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=_ubzEPyQUIT&" +
                        "codes=MqV3m7XfW9")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_43() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/rnkY?" +
                        "fields=fUxLyz&" +
                        "fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/O")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/uPdLY4il0M?fields=mSHpsk")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/s")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=fbFw9_&" +
                        "codes=P")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/1wIxCfHCZu")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/fGGgB39rsQ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_44() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/KFLuQ7LpVJifeJ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/357")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/r58v%60Hp7")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/evom%60ster_10827_input?fields=mI6K")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/evomaster_11062_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/Sj%5Ca?fields=%C2%80so")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/FNZdF?fields=VKBv")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/c4?fields=XtdTdonNcpGRMa1")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=ld7&" +
                        "codes=2yO9cAP")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=ztDRGh3Dkb%3BNAe2")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_45() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/2Kw36yq5B1W4Ewo")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/r?" +
                        "fields=m4b6SosP2qAN&" +
                        "fullText=false")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/OGg?fields=vQEzg")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/LYpvDqb_xh2Zu3")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/PEjTi")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/qjJU1W2b56")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=iSG")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=Ner")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/TL2IsN56Gbpss")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_46() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/S79Unl96qrR1Q?fields=4G0FYDfOWLT")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/YB7fkDX")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/Vj2Vj?fields=bO272i2B")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/guatemala?" +
                        "fields=evomaster_33_input&" +
                        "fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/evomaster_34_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/c_")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/rsOn6pBRh?fields=")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=iD6WK")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/evomaster_35_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/evomaster_36_input?fields=evomaster_19_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_47() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/S79Unl96qrR1Q?fields=4G0FYDfOWLT")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/YB7fkDX")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/Vj2Vj?fields=bO272i2B")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/guatemala?" +
                        "fields=evomaster_33_input&" +
                        "fullText=false")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/eUoUasteUU1U_inUUt")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/C_")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/central%20asia?fields=")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=iD6WK")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/evomaster_35_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/evomaster_36_input?fields=evomaster_19_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_48() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/N8YEt")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/fzV")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/k7050imyXyPBPS?fields=xfkINZGq6WA")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/mB73qOUbpe")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/h_2_CP")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/jXL")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/T")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/4zkHOGDF9L9K")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_49() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/yKBiEPWl2")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/nV")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/GpM2V")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/IGS")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=Nnpt&" +
                        "codes=GqJVUTu")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=sTX")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_50() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/evomaster_828_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/evomaster_829_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/goWNZ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=xfiBhkxwPR")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/evomaster_830_input?fields=bmkLDcMmo")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/Y?fields=ZE0w8Gk60a")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/se?fields=zU2V84UqJJ")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_51() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=7VsZHGfW")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/aF3DtkRn7v")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/fs4wAa?fields=jiqoK_IHQhOH6")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/ng6")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/yFlYa0EznHOdjt?fields=qUIs8dibMMMM")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/uP?fields=EVy")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=FpNC")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=kKqIbuST3IM")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_52() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_53() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/S79Unl96qrR1Q4")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/YB7fkDX")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/Vf2Vj")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/OPzidDKi6GTV?" +
                        "fields=WE&" +
                        "fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/kCNFKdzsSL8I15c")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/c_")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/ZqZPm?fields=")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=iD6WK")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/UQFqLLb_zrk6")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/mMLvLa?fields=Jgg")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_54() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=7y")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_55() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=evokasterU%3A3U%3A_inpuU")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_56() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/%5Cfp?fields=opbq8ESEtIT")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }


    @Test
    public void test_57() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/i%5C?fullText=true")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }


    @Test
    public void test_58() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/%5C")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }


    @Test
    public void test_59() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=UhT&" +
                        "codes=")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_60() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/9Z4Z7z4yIoijk_6h?fields=2aiepdkzcRm")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/iSdsweAZuuraVdz")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=C")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/265kvyl9xJ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_61() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/1scT2tE2")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/TUU%5C5_UUUU")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/Ohp2Rv")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/evomaster_4201_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_62() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/yPuqHUp9Qcl")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/FMIL2hFFzjd")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/5DGuTPQML")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/jRBPftELU8to6FR0?fields=dLvzo6")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/%5Cv")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }


    @Test
    public void test_63() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/xM%5CEKDzg?" +
                        "fields=QYQb7GgrmLuH&" +
                        "fullText=true")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/evomaster_8128_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/Ohp2Rv")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/evomaster_8129_input?fields=BgaGtx8KjVdaJV")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_64() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/1xX8wZ5%5C69")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/evomaster_9163_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/evomaster_9164_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=evomaster_9165_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_65() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/gA84Hrfk?fields=9i")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/NaF3X17ukq9")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/5HWVoGsUPCxTT7rq?fields=8S4fPKaEMxyq9")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/kk20iaMJrpG")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/W?fields=XH1q")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/u0o9xgY9qsue2ZQ")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_66() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" +
                        "fields=S9Ug8MQN&" +
                        "codes=w")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_67() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/X_qBi?fields=TF08UzeS")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_68() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/Fgo8mVpLnl")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_69() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/Vakq?fields=pgszv1")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_70() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/L")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_71() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/SIqOz")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=AV9XYp")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/dUV6l6LX")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/55dCn?fields=YPkAC9CdmxaF4s8")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/TN95MLKxadU7qms?fullText=false")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/znW")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/MirH51Jt0lW8Y?" +
                        "fields=x8ZmQyLg8qAjs&" +
                        "fullText=false")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/Xv7yc4iD")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/PT?fields=kNq_9QcVX8eAOoZ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_72() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/FfU8uPW")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/ywSUV08ZH2mf")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/atm")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/mQ1Q5ATi77cLqs")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/IJkQSuPT")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/xZgpa")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/lm")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_73() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/z8a")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_74() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/QV?fields=0")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_75() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/akl")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_76() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/77d")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_77() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/XYJVYiqIAJy")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_78() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/e6lLV1NoqX789d")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_79() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/cU9ocd4UfF0_d_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_80() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/A3K")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_81() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/UrrjfAgww?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_82() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/9m_k3R1_b")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_83() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/QbOam?fields=TaH7CFw2")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_84() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/1?fields=e0Iai")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_85() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/8bJpayz_FJe2qS?fields=4vUAp6tAVnDke")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_86() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/V_U10NcwCHr6G96?fields=7UfJ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_87() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/J9tWTCxrf_Hvecdv?fields=qCQXmNoHuQtZ7")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_88() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/29raNyEaJbyK")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/8aySXkC0aTW7RRk")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/F3RN4Bq")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/UodvjaIToeh5GneY")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/RRDnYF5oHD7XAP")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/2bmIc9TN3uhc")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/2Pz8XC4kc8FOgXfI")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_89() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/Uc8?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_90() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/uzz37L")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


    @Test
    public void test_91() throws Exception {

        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/1UpuU9yZGd")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


}
