import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.evomaster.client.java.controller.api.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import static org.evomaster.client.java.controller.db.dsl.SqlDsl.sql;
import  org.evomaster.client.java.controller.api.dto.database.operations.InsertionDto;
import  java.util.List;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
 * This file was automatically generated by EvoMaster on 2020-11-23T16:09:37.731+01:00[Europe/Paris]
 * <br>
 * The generated test suite contains 73 tests
 * <br>
 * Covered targets: 1270
 * <br>
 * Used time: 0h 1m 0s
 * <br>
 * Needed budget for current results: 90%
 * <br>
 * 
 */
public class EvoMasterTest_1m {

    
    private static final SutHandler controller = new eu.fayder.restcountries.EMDriver();
    private static String baseUrlOfSut;
    
    
    @BeforeClass
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterClass
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @Before
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    @Test
    public void test_0_with500() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=SOFwAm&" + 
                    "codes=ovC")
                .then()
                .statusCode(500) // eu/fayder/restcountries/v2/rest/CountryRest_268_getCountriesJson
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/EDedHf8g?fullText=false")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/Yz09ihSm6oqOE")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/s8KPnj1Y")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_1() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/micronesia")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_2() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/225")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_3() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/CaIS?fields=R")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_4() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/m?fields=")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_5() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/oceania")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_6() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=nic")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_7() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/western%20asia")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_8() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=K1")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_9() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/est")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_10() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/Vi")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_11() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/Sek")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_12() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/EaEU?fields=P")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_13() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/sahrawi?fields=Asr_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_14() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/es?fields=WMFLpmu6I9708hI")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_15() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=8aJf&" + 
                    "codes=hwbnnY2LKM")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/Q")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/626lhnEnQ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_16() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/L_tU1rtfZOuCW?fields=St1EKEYhVeVKIC")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/TtW")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=K1")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_17() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=8aJf&" + 
                    "codes=OwJihvNg1tRsF8")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/anguilla")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/bG")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/626lhnEn")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_18() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/bangkok")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/sB")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=l9&" + 
                    "codes=bO0esi0BQ9TDnJ")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/lqNd4QbQem9Tcn03?fields=K5BsR2")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/A_1NevH_S%5CslG4aG")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }
    
    
    @Test
    public void test_19() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/I")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/zyASUaky42cNGvUe")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/nGq_mukyRkTkv")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/JbfekuJf3X")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/qGBh9gZ0")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_20() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=8aJf&" + 
                    "codes=OwJihvNg1tRsF%3A")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/anguilla?fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/9ey")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/bI?fields=k5gSope")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/626lhnE")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_21() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/y2gRCx6yaOMwaQ")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=o8CBtCSOqHAR6")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=uLelYVH")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/y")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/z")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=ScCVT9m")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_22() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=l8W")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_23() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/evomaster_283_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/sB")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=l9&" + 
                    "codes=evomaster_285_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/lqNd4QbQem9Tcn03")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/A_1NevH_SZslG4aG")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_24() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_25() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/Rfayi?fields=BMWc1kbk069NMI6m")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/SIC8")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/ft0itg")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/MBeNh8YOXT")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=7riTd")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/TGtsv57MO3NciAH1")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/v_6PQ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=V")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/T49HeG_Xutt1wc")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_26() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/2lXqf_aH3K?fields=HUcLCUIB")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/evomaster_494_input?fields=TWs")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/_e")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/evomaster_496_input?fields=JDhkJN75bwb892")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/mKA")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/evomaster_497_input?fullText=false")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=logRgIfioyMU")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/v")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_27() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/americas?fields=ihQQrIu")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/evomaster_184_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/98")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/HYd3A")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=evomaster_186_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/9DwPGakNK9?fields=MH")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_28() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=per2ui%3BTTlNoCQFn")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/rZQQ8R1s_MHAp9g?fields=4v")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/evomaster_142_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/evo%5Daster_143_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/S5")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/8gDvWhfU8iKhaX?fields=Bv8v")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/UUu")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/evomaster_271_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/evomaster_145_input?fields=evomaster_144_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_29() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=8aJf&" + 
                    "codes=evomaster_292_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/evomaster_290_input?fields=8jct")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=tu")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/km?fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/626lhnEna")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_30() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=per2ui3TTlNoCQFn")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/rVQQ8R1s_MHAp9g")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/eastern%20asia")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/evo%5Daster_143_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/8gDvWhfU8iKha?fields=Bv8v")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/evomaster_151_input?fields=evomaster_150_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/BIhHmofV?fields=evomaster_149_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_31() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=per2ui3TTlNoCQFn")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/rZQQ8R1s_MHAp9g?fields=4v")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/eastern%20asia")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/evo%5Daster_143_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/S5")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/8gDvWhfU8iKhaX")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=R")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/IfN")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/TFCT")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/evomaster_145_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_32() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/oceania?fields=kXsVkJ4cUhvQK0F")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/evomaster_111_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/5ZD7tG36VQ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/0UbPke?fields=XVyd_bXmM8hyhqGU")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/axwKq5M1RBp")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/evomaster_112_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/evomaster_58_input?fields=1hwEy4SjF")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_33() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/evomaster_340_input?fields=evomaster_339_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/cT0N4nq?fields=xMTcI")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/597")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/evomaster_334_input?fields=evomaster_158_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/evomaster_335_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/evomaster_336_input?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=cuPGXFoyCsWc3Qr&" + 
                    "codes=evomaster_337_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/J8dUUrx%3E")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/jgh?fields=jWqw1woh")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/saint%20kitts%20and%20nevis?" + 
                    "fields=evomaster_338_input&" + 
                    "fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_34() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/FPiJ?fields=E6wBfN00")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/cT0N4nq?fields=xMcI")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/evomaster_157_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/evomaster_334_input?fields=evomaster_158_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/evomaster_335_input")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/evomaster_336_input?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=evomaster_337_input")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/J8dUUrx%3E")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/jgh?fields=jWqw1woh")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/saint%20kitts%20and%20nevis?" + 
                    "fields=evomaster_338_input&" + 
                    "fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_35() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/G0")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/jt")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/Z72?fields=z6uwfkrS")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/4oQiIoUc1Vo6?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/Doj6X7yBXLSz0?fields=Ltgq22")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=gXZog")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_36() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all?fields=y5jo")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/8bd7A")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/PPp27IhAf6I1W")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/BwNlqEb8?fields=uW")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/fpi")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/ys8ZIP8k77?fields=lmy")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=Ujl")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/Y")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/ZnSuEiDmcn8HuRz8?fields=NoAtSj")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_37() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=8aJf&" + 
                    "codes=OwJihvNg1tRsF8")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/anguilla?fullText=true")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/bG?fields=k5gSope")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/626lhnEn")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_38() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_39() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/2lXqf_aH3K?fields=HUcLCUIB")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/zZND?fields=TWs")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/_")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/Dyf5ftrCQyg5VfY?fields=JDhkJN75bwb892")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/jJA")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/taDYT")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/Dx7Z")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/v?fields=Nol_G")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_40() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=K1")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/all")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_41() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/ei?fields=sx")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_42() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/%5CN?fields=")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
    }
    
    
    @Test
    public void test_43() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=pR_Cmg99qV")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/g%5CqybWbI79Oh")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");;
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=PeWaNuXcx")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/NOgZcn3m")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_44() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/ZLMbsX1kfmvepUjF?fields=6BdlmBhHvWGh")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/ONIjVJ9Pgs")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/UX_18fqmCPpqLr?fields=SJ6pPI")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/SYyPYkfOL0n")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_45() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/Q3NByOdkB6fgtJF")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_46() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/ygwjocsW_iuErLP")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_47() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/OzMWC6uba8IV9Mhe?fields=NWZNBf9sSIz7v")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_48() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?" + 
                    "fields=MG8y&" + 
                    "codes=pcXpxGa")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_49() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/L")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_50() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=p_FQfVamyCm")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_51() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/ZOJrNEyUu")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/OWW?fields=_jzdrRZbkm9xFof")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha?codes=")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/Uxi9mT_U9k2?fields=DyvriVS")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/RP")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=hnTUGMSMzzIYeIrN")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/bnnP7Z")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/Y8dRfv2doTycR9p0")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/7GB99r7AoNvTqx2")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/g0VB5dhl")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_52() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/EFManAaKQArkaTkG")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/YQn?fields=K3wNsV")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/cromzDl5ESFz")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/1xXE8?fields=ruIwEdUZR5_n")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/39NzRDt12fY")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/BJANBosdTb6t")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha/HfF")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_53() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=per2ui3TTlNoCQFn")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/rZQQ8R1s_MHAp9g?fields=4v")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/vm5uaVWz2e")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/YpdKvQ")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/8gDvWhfU8iKhaX")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/If")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/NQvAx?fields=bx3iPgrzi11gI")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_54() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=OjOO3AWUgM8p")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/Xh?fullText=false")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/JEd8WIMF")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/gGMs8tu?fields=4upH")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=uxlDV3w3XSCni")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/Aexa")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/alpha/svURj88?fields=")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/currency/ebz")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/ED3lsT8u1iA")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_55() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/TJUbz0NHIgs79Ilm?fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/ZH0xaoSA3A")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/ry6fCQnb")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/P")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/F2r5beQOmUQQOAdj")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/alpha?codes=CPzz")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/6bwD8F5Xao2yD")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/fKyRtLPGhcX?" + 
                    "fields=IuXMtKhDvE1&" + 
                    "fullText=true")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/vKqCfI0nzligfh5O")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json");
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/ztcVNdLHmi_9BXDB")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_56() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/currency/Seg")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_57() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/;bDU?fields=T")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("");
    }
    
    
    @Test
    public void test_58() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/subregion/E3Jpzl_tg1QO")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_59() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/region/FPDhH")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_60() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/capital/EKtE")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_61() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/callingcode/KrZQrk8vklnBy")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_62() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/name/gQQNz")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_63() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/9UJ")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_64() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/lang/QXEcGnkaizPQ?fields=WMFLpmu6I9708hI")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_65() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/subregion/QYTM")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_66() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/region/ijjckG8W70r146QS?fields=bnKjwYx8Sl")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_67() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/capital/Yhgx8uKT9B7l")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_68() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/demonym/XEbd9ttbYhzgOt")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_69() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/callingcode/qXRG6RSHYUf")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_70() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/name/Sig4CYMpQ4_X?" + 
                    "fields=8q0&" + 
                    "fullText=false")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_71() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v1/lang/cNF1pPtMVM0")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }
    
    
    @Test
    public void test_72() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rest/v2/regionalbloc/SbJX6D99Urj?fields=GnXV3I6JHh")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json");
    }


}
